# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/RV32IM/RV32IM.srcs/sources_1/ip/blk_memory/blk_memory.xci
# IP: The module: 'blk_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/RV32IM/RV32IM.srcs/sources_1/ip/blk_memory/blk_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/RV32IM/RV32IM.srcs/sources_1/ip/blk_memory/blk_memory.xci
# IP: The module: 'blk_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/RV32IM/RV32IM.srcs/sources_1/ip/blk_memory/blk_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
